apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_deploy_project2
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: project2-pod  
  template:
    metadata: 
      labels:
        app: project2-pod
    spec: 
      containers: 
      - name: project2-cont
        image: mehta14/java-project1:latest
        ports:
        - containerPort: 9090
